- name: Deploy Nginx with dynamic HTML and cowsay
  hosts: all
  become: true
  vars:
    message: "This is server {{ ansible_hostname }}!"
  tasks:
    - name: Install Nginx and cowsay
      apt:
        name:
          - nginx
          - cowsay
        state: present
        update_cache: true

    - name: Run cowsay with server message
      ansible.builtin.command: cowsay "{{ message }}"
      register: cowsay_result

    - name: Deploy HTML file with dynamic content
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted
        enabled: true