---
- name: Set up server environment
  hosts: servers
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - update
        - all

    - name: Install required packages
      apt:
        name:
          - git
          - make
          - nodejs
        state: present
      tags:
        - packages
        - all

    - name: Create user arya
      user:
        name: arya
        state: present
      tags:
        - users
        - all

    - name: Create user sansa
      user:
        name: sansa
        state: present
      tags:
        - users
        - all

    - name: Create user tirion
      user:
        name: tirion
        state: present
      tags:
        - users
        - all
