---
- name: Install and configure Nginx
  hosts: servers
  become: true

  vars:
    nginx_html_path: /usr/share/nginx/html/index.html
    nginx_conf_path: /etc/nginx/nginx.conf

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy HTML page
      copy:
        src: files/index.html
        dest: "{{ nginx_html_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Copy Nginx config
      copy:
        src: files/nginx.conf
        dest: "{{ nginx_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
