- name: Add Node.js apt repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource
    update_cache: true

- name: Install Node.js
  apt:
    name: nodejs
    state: present
